In [25]:
import pandas as pd
from sklearn.linear_model import LinearRegression
dt = {
    "Name":["rahul","aman","rohit","neha","priya"],
    "Dipartment":["IT","IT","HR","HR","IT"],
    "Year":[2023,2024,2023,2024,2023],
    "Salary":[50000,60000,45000,55000,70000]
}
df = pd.DataFrame(dt)
df["Name"] = df["Name"].str.title()

In [26]:
df.sample(2)

    Name Dipartment  Year  Salary
1   Aman         IT  2024   60000
0  Rahul         IT  2023   50000

In [27]:
dt =df.pivot_table(
    values="Salary",
    index="Dipartment",
    columns="Year",
    aggfunc="mean",
   
    
    
)
print(dt)

Year           2023     2024
Dipartment
HR          45000.0  55000.0
IT          60000.0  60000.0

In [28]:
#dt= df.pivot(index = "Name",Coulmns = 'Year')["Salary"].max()

In [29]:
#df.pivot(index ='Dipartment',columns='Year')["Salary"]
#df.pivot(index ='Dipartment',columns='Year')["Salary"]

In [30]:
df[df.duplicated(subset=["Dipartment", "Year"], keep=False)]

    Name Dipartment  Year  Salary
0  Rahul         IT  2023   50000
4  Priya         IT  2023   70000

In [31]:
df.to_excel("Office_Sellery.xlsx",index=False)

In [32]:
#data_2 = {
#    "Age":[20,25,30,35,40]
#}
#dff = pd.DataFrame(data)
#print(dff)

In [33]:
df.sample(2)

    Name Dipartment  Year  Salary
0  Rahul         IT  2023   50000
4  Priya         IT  2023   70000

In [34]:
from scipy import stats
import seaborn as sns
flights = sns.load_dataset("flights")
print(flights)

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [35]:
#X = df[["Dipartment"]]
#y = df["Salary"] 

#model = Linear_Regression
#model.fit(X,y)

In [36]:
import seaborn as sns
import matplotlib.pyplot as plt
sns.regplot(x="Dipartment",y="Salary",data=dt)

plt.ylim(0,)

KeyError: 'Dipartment'